SPLIT_KEYBOARD = yes
ENCODER_ENABLE = no
RGBLIGHT_ENABLE = yes
OLED_DRIVER_ENABLE = no
CONSOLE_ENABLE = no
RGBLIGHT_ANIMATIONS = no
COMBO_ENABLE = yes
NKRO_ENABLE = no
AUDIO_ENABLE = no
RGB_MATRIX_ENABLE = no

# Space savers
LTO_ENABLE = yes
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no

SRC += rgblight.c
